infoapp/urls.py
from django.urls import path
from infoapp import views


app_name = 'info'
urlpatterns = [
    path('home/',views.home,name='home'),
    # path('add/',views.add,name='add'),
    path('add_logic/',views.add_logic,name='add_logic'),
    path('delete/',views.delete,name='delete'),
    path('update/',views.update,name='update'),
    path('update/',views.update,name='update'),
    path('load_update/',views.load_update,name='update'),
    path('update_logic/',views.update_logic,name='update_logic'),
    path('fun/',views.fun,name='fun'),
]

loginapp/urls.py
from django.urls import path
from loginapp import views
app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    # path('register/', views.register, name='register'),
    path('register_logic/', views.register_logic, name='register_logic'),
    path('getcaptcha/', views.getcaptcha, name='captcha'),
    path('check/', views.check, name='check'),
    path('check_capt/', views.check_capt, name='check_capt'),
]

reems/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('loginapp.urls')),
    path('info/',include('infoapp.urls')),
]

infoapp/models.py
from django.db import models


# Create your models here.
class Info(models.Model):
    name = models.CharField(max_length=20)
    salary = models.DecimalField(max_digits=7,decimal_places=2)
    age = models.SmallIntegerField()
    head = models.ImageField(upload_to='pics')

loginapp/models.py
from django.db import models


# Create your models here.
from django.shortcuts import render, redirect
from django.utils.deprecation import MiddlewareMixin


class User(models.Model):
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    real_name = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)

    class Meta:
        db_table = 'user'


class MyMiddleware(MiddlewareMixin):
    def __init__(self, get_response):
        super().__init__(get_response)
        # print("init1")

    def process_request(self, request):
        if "login" not in request.path:
            # print("登录验证")
            session = request.session
            if session.get("login"):
                print("已登录")
            else:
                # print("未登录")
                return redirect('login:login')
        else:
            print("正在登录")

#     def process_view(self, request, view_func, view_args, view_kwargs):
#         print("view:", request, view_func, view_args, view_kwargs)
#
#     def process_response(self, request, response):
#         print("response:", request, response)
#         return response
#
#     def process_exception(self, request, ex):
#         print("exception:", request, ex)

infoapp/views.py
import os
import uuid

from django.core.paginator import Paginator
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render, redirect,HttpResponse
from django.urls import reverse

from infoapp.models import Info


# Create your views here.
def user_default(u):
    if isinstance(u,Info):
        return {'id':u.id,'name':u.name,'age':u.age,'salary':str(u.salary),'head':str(u.head)}


def home(request):
    login = request.session.get('login')
    if login:
        info = list(Info.objects.all())
        return JsonResponse({'info':info},json_dumps_params={"default":user_default})
    return HttpResponse('×')


# def add(request):
#     return render(request, 'info/../static/addEmp.html')


def generateUUID(headname):
    id = str(uuid.uuid4())
    extend = os.path.splitext(headname)[1]
    return id+extend


def add_logic(request):
    try:
        name = request.POST.get("name")
        salary = request.POST.get("salary")
        age = request.POST.get("age")
        # print(name,age,salary)
        headpic = request.FILES.get("picture")
        if headpic:
            ext = os.path.splitext(headpic.name)
            headpic.name = str(uuid.uuid4()) + ext[1]
        with transaction.atomic():
            # print(name,salary,age,headpic)
            Info.objects.create(name=name, age=age, salary=salary, head=headpic)
            return HttpResponse('√')
    except:
        return HttpResponse('×')


def delete(request):
    id = request.GET.get("id")
    # print(id)
    emp = Info.objects.get(id=id)
    if emp:
        emp.delete()
        return HttpResponse(1)


def update(request):
    id = request.GET.get("id")
    ems = Info.objects.get(id=id)
    # print(id)
    if ems:
        request.session["updateId"] = id
        return HttpResponse(1)
    return HttpResponse(0)


def load_update(request):
    param = request.GET.get("param")
    # print(param)
    id = request.session.get(param)
    info = Info.objects.get(id=id)
    return JsonResponse({'info':info},safe=False,json_dumps_params={'default':user_default})


def fun(request):
    return HttpResponse('1')

def update_logic(request):
    # print('dfg')
    try:
        with transaction.atomic():
            id = request.POST.get("eId")
            print(id)
            ems = Info.objects.get(id=id)
            ems.name = request.POST.get("name")
            ems.salary = request.POST.get("salary")
            ems.age = request.POST.get("age")
            headpic = request.FILES.get("headpic")
            print(id,ems.name,ems.salary,ems.age,headpic)
            if headpic:
                ext = os.path.splitext(headpic.name)
                headpic.name = str(uuid.uuid4()) + ext[1]
                ems.head = headpic
                # picture()
                print(id, ems.name, ems.salary, ems.age, headpic)
                ems.save()
            return HttpResponse('1')
    except:
        return HttpResponse(0)

loginapp/views.py
import os
import uuid

from django.db import transaction
from django.shortcuts import render, HttpResponse, redirect
from loginapp.models import User
import random, string
from loginapp.captcha.image import ImageCaptcha


# Create your views here.
def login(request):
    name = request.COOKIES.get('username')
    pwd = request.COOKIES.get('password')
    user = User.objects.filter(name=name, password=pwd)
    if user:
        request.session['login'] = 'ok'
        return redirect('info:home')
    return render(request, 'login/login.html')


def login_logic(request):
    print('hhhh')
    name = request.POST.get('name')
    pwd = request.POST.get('pwd')
    rem = request.POST.get('remember')
    user = User.objects.filter(name=name, password=pwd)
    if user:
        respond = HttpResponse('√')
        if rem:
            respond.set_cookie('username', name, max_age=7 * 24 * 3600)
            respond.set_cookie('password', pwd, max_age=7 * 24 * 3600)
        request.session['login'] = 'ok'
        return respond
    else:
        return HttpResponse('×')


# def register(request):
#     return render(request, 'login/regist.html')


def generateUUID(headname):
    id = str(uuid.uuid4())
    extend = os.path.splitext(headname)[1]
    return id + extend


def register_logic(request):
    try:
        name = request.POST.get('username')
        real_name = request.POST.get('name')
        pwd = request.POST.get('pwd')
        sex = request.POST.get('sex')
        print(name, real_name, pwd, sex)
        with transaction.atomic():
            User.objects.create(name=name, real_name=real_name, password=pwd, sex=sex)
        return HttpResponse('√')
    except:
        return HttpResponse('×')


def check(request):
    print('dfgsdf')
    name = request.GET.get('name')
    print(name)
    result = User.objects.filter(name=name)
    print(result)
    if result:
        return HttpResponse('×')
    else:
        return HttpResponse('√')


def getcaptcha(request):
    image = ImageCaptcha(fonts=[os.path.abspath('loginapp/captcha/FZZJ-KFTXKJW.TTF')])
    code = random.sample(string.ascii_letters + string.digits, 4)
    random_code = ''.join(code)
    request.session['code'] = random_code
    print(random_code.lower())
    data = image.generate(random_code)
    return HttpResponse(data, 'image/png')


def check_capt(request):
    capt = request.GET.get('number')
    print(capt)
    capt2 = request.session.get('code').lower()
    print(capt2)
    if capt == capt2:
        return HttpResponse('√')
    else:
        return HttpResponse('×')

templates/info/addEmp.html
<html>
{% load static %}
	<head>
		<title>add Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css"
			href="{% static 'css/style.css' %}" />
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p>
								2009/11/20
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">Main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						add Emp info:
					</h1>
					<form action="{% url 'info:add_logic' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									name:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									salary:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									age:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" />
								</td>
							</tr>
                            <tr>
								<td valign="middle" align="right">
									headpicture:
								</td>
								<td valign="middle" align="left">
									<input type="file" class="inputgri" name="picture" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Confirm" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/info/emplist.html
<html>
	<head>
        {% load static %}
		<title>emplist</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <style>
        .a{
            width:20px;
            height: 20px;
            border:1px solid #74A8F5;
            cursor:pointer;
            display: inline-block;
            text-align: center;
            line-height: 20px;
        }
        .b{
            border:0;
            width:20px;
            height: 20px;
            cursor:pointer;
            display: inline-block;
            text-align: center;
            line-height: 20px;
        }
        a{
            text-decoration:none;
        }
</style>
	</head>
	<body>
		<div id="wrap">
			<div id="top_content"> 
				<div id="header">
					<div id="rightheader">
						<p class="date">
							2009/11/20

							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						Welcome!
					</h1>
					<table class="table">
						<tr class="table_header">
							<td>
								ID
							</td>
							<td>
								Name
							</td>
							<td>
								Salary
							</td>
							<td>
								Age
							</td>
                            <td>
								Headpic
							</td>
							<td>
								Operation
							</td>
						</tr>

                        {% for i in page %}

						<tr class="row1">
							<td >
                                {{ forloop.counter }}
							</td>
							<td>
								{{ i.name }}
							</td>
							<td>
								{{ i.salary }}
							</td>
							<td>
								{{ i.age }}
							</td>
                            <td>
                            {% load static %}
								 <img src="{%  static  i.head.url %}" height="50px">
							</td>
							<td>
								<a href="{% url 'info:delete' %}?id={{ i.id }}&number={{ page.number }}">delete emp</a>&nbsp;<a href="{% url 'info:update' %}?id={{ i.id }}&number={{ page.number }}">update emp</a>
							</td>
                        </tr>
                        {% endfor %}
                        </table>
                {% if page.has_previous %}
                    <a href="{% url 'info:home' %}?number={{ page.previous_page_number }}">上一页</a>
                {% endif %}
                {% for p in page.paginator.page_range %}
                    {% if p == page.number %}
                        <a href="{% url 'info:home' %}?number={{ page.number }}" class="a">{{ p }}</a>
                        {% else %}
                        <a href="{% url 'info:home' %}?number={{ page.number }}" class="b">{{ p }}</a>
                    {% endif %}
                {% endfor %}
                 {% if page.has_next %}
                    <a href="{% url 'info:home' %}?number={{ page.next_page_number }}">下一页</a>
                {% endif %}
					<p>
						<input type="button" class="button" value="Add Employee" onclick="location.href='{% url 'info:add' %}'"/>
					</p>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/info/updateEmp.html
<html>
    {% load static %}
	<head>
		<title>update Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css"
			href="{% static 'css/style.css' %}" />
	</head>

	<body>
    {% load static %}
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p>
								2009/11/20
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">Main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						update Emp info:
					</h1>
					<form action="{% url 'info:update_logic' %}?id={{ info.id }}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									id:
                                    <input type="hidden" class="inputgri" name="id" value="{{ info.id }}">
                                    <input type="hidden" class="inputgri" name="number" value="{{ number }}">
								</td>
								<td valign="middle" align="left">
                                    {{ info.id }}
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									name:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" value="{{ info.name }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									salary:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" value="{{ info.salary }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									age:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" value="{{ info.age }}"/>
								</td>
							</tr>
                            <tr>
								<td valign="middle" align="right">
									headpicture:
								</td>
                                <td valign="middle" align="left">
                                    <img src="{%   static info.head.url %}" alt="" height = "50px">
                                </td>
							</tr>
                            <tr>
                                <td valign="middle" align="right">
                                    new_headpicture
                                </td>
                                <td valign="middle" align="left">
									<input type="file" class="inputgri" name="picture" />
								</td>
                            </tr>
						</table>
						<p>
							<input type="submit" class="button" value="Confirm" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/login/login.html
{% load static %}
<html>
	<head>
        {% load static %}
		<title>login</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <script src="{% static 'Jq/jquery-1.11.1.js' %}"></script>
        <script>
            function login() {
                $.ajax({
                    type: 'post',
                    url: '{% url 'login:login_logic' %}',
                    data: $('#form').serialize(),
                    success: function (data) {
                        if (data === '√'){
                            location.href='{% url 'info:home' %}'
                        }else {
                            alert('用户名或密码错误')
                        }
                    }
                })
            }
        </script>
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p>
								2009/11/20
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						login
					</h1>
					<form action="{% url 'login:login_logic' %}" method="post" id="form">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									username:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									password:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" />
								</td>
							</tr>
						</table>
                        <p>
							<input type="checkbox" class="button" value="1" name="remember">记住我
						</p>
						<p>
							<input type="button" class="button" value="Submit &raquo;" onclick="login()"/>
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/login/regist.html
<html>
	<head>
         {% load static %}
		<title>register</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <script src="{% static 'Jq/jquery-1.11.1.js' %}"></script>
        <script>
            flag1 = false;
            flag2 = false;
            flag3 = false;
            function fun1() {
                $('#span').html('<img src="{% static 'images/5-121204194025.gif' %}" height="20px">');
                $.ajax({
                    type: 'post',
                    url: '{% url 'login:check' %}',
                    data: 'name='+$('#name').val()+'&csrfmiddlewaretoken={{ csrf_token }}',
                    success : function (msg) {
                        if (msg === '×'){
                            flag1 = false;
                            $('#span').html('<img src="{% static 'images/error_3.jpg' %}" height="20px">'+'用户名已存在' )
                        }else if(msg === '√'){
                            flag1 = true;
                            $('#span').html('<img src="{% static 'images/right.jpg' %}" height="20px">' )
                        }
                    }
                })
            }
            function fun2() {
               let pwd1 = $('#pwd1').val();
               let pwd2 = $('#pwd2').val();
               if (pwd1 === pwd2){
                   flag2 = true;
                   $('#span2').html('<img src="{% static 'images/right.jpg'%}" height="20px">')
               }else{
                   flag2 = false;
                   $('#span2').html('<img src="{% static 'images/error_3.jpg'%}" height="20px">'+'两次密码输入不一致')
               }
            }
            function fun3() {
                $('#span3').html('<img src="{% static 'images/5-121204194025.gif' %}" height="20px">');
                $.ajax({
                    type: 'get',
                    url: '{% url 'login:check_capt' %}',
                    data: 'number='+$('#number').val(),
                    success: function (msg) {
                        if (msg === '√'){
                            flag3 = true;
                            $('#span3').html('<img src="{% static 'images/right.jpg' %}" height="20px">');
                        }else {
                            flag3 = false;
                            $('#span3').html('<img src="{% static 'images/error_3.jpg' %}" height="20px">'+'验证码输入有误');
                        }
                    }
                })
            }
            function register() {
               if (flag1===true && flag2===true && flag3===true){
                   $.ajax({
                       type: 'post',
                    url: '{% url 'login:register_logic' %}',
                    data: $('#form1').serialize(),
                    success: function (data) {
                        if (data === '√'){
                            location.href='{% url 'login:login' %}'
                        }else {
                            alert('注册失败')
                        }
                    }
                   })
               }
            }
        </script>
	</head>
	<body>

		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p>
								2009/11/20
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>

            <div id="header">
				<div id="content">
					<p id="whereami">
					</p>

					<h1>
						注册
					</h1>
					<form action="{% url 'login:register_logic' %}" method="post" enctype="multipart/form-data" id="form1">
                         {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="username" id="name" onblur="fun1()"/>
                                    <span  id="span"></span>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									真实姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" id="pwd1" name="pwd"/>
								</td>
							</tr>
                            <tr>
								<td valign="middle" align="right">
									确认密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" id="pwd2" onblur="fun2()"/>
                                    <span id="span2"></span>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									性别:
								</td>
								<td valign="middle" align="left">
									男
									<input type="radio" class="inputgri" name="sex" value="m" checked="checked"/>
									女
									<input type="radio" class="inputgri" name="sex" value="f"/>
								</td>
							</tr>
							<tr>
                                <td valign="middle" align="right">
                                     验证码:
                                </td>
                                <td valign="middle" align="left">
									<input type="text" class="inputgri" id="number" onblur="fun3()"/>
                                    <span id="span3"></span>
								</td>
								<td valign="middle" align="right">
                                    <img src="{% url 'login:captcha' %}" alt="" width="80px" height="30px" id ="num">
                                    <a href="javascript:void(0)" onclick="document.getElementById('num').src='{% url 'login:captcha' %}?'+(new Date()).getTime()">换一张</a>
								</td>
							</tr>
						</table>
						<p>
							<input type="button" class="button" value="Submit &raquo;" onclick="register()"/>
						</p>
					</form>
				</div>
			</div>

			<div id="footer">
				<div id="footer_bg">
				ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>